name: g_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  dio: ^5.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo3.png" 
  min_sdk_android: 21 

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo3.png
    - assets/images/logo_name.png
    - assets/images/splash.png
    - assets/images/star(1).png
    - assets/images/bag.png
    - assets/images/discount.png
    - assets/images/coupon.png
    - assets/images/logout.png
    

  fonts:
    - family: Judson
      fonts:
        - asset: assets/fonts/Judson-Regular.ttf
          weight: 400
        - asset: assets/fonts/Judson-Bold.ttf
          weight: 700
